[variables]
NIXPACKS_NO_MUSL = "1"

[phases.setup]
nixPkgs = [
  "nodejs-18_x",
  "chromium",
  "nss",
  "freetype",
  "harfbuzz",
  "ca-certificates",
  "ttf-freefont"
]

[phases.install]
cmds = ["npm ci --only=production"]

[phases.build]
cmds = ["echo 'No build step required'"]

[start]
cmd = "node server.js"
