[build]
builder = "NIXPACKS"

[start]
cmd = "node scheduler.cjs"

[phases.setup]
nixPkgs = [
  "nodejs_20",
  "chromium",
  "freetype",
  "harfbuzz",
  "ca-certificates",
  "glib",
  "nss",
  "alsa-lib",
  "fontconfig",
  "libxcomposite",
  "libxdamage",
  "libxrandr",
  "libxcb",
  "gtk3"
]

[env]
PUPPETEER_EXECUTABLE_PATH = "/nix/store/*chromium*/bin/chromium"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
