[build]
builder = "NIXPACKS"
cmd = "node scheduler.cjs"

[phases.setup]
nixPkgs = ["nodejs", "chromium"]

[phases.install]
cmds = ["npm install"]

[env]
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
