[build]
builder = "NIXPACKS"

[start]
cmd = "node scheduler.cjs"

[phases.setup]
nixPkgs = [
  "chromium",
  "freetype",
  "fontconfig",
  "glib",
  "nss",
  "alsa-lib",
  "harfbuzz",
  "ttf-dejavu",
  "ttf-font-awesome",
  "gtk3",
  "libxcomposite",
  "libxdamage",
  "libxrandr",
  "libxcb"
]

[phases.install]
cmds = ["npm install"]

[env]
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
