[build]
  builder = "NIXPACKS"
  cmd = "node scheduler.cjs"

[phases.setup]
nixPkgs = [
  "chromium",
  "nss",
  "alsa-lib",
  "harfbuzz",
  "freetype",
  "ttf-font-awesome",
  "ttf-dejavu",
  "glib",
  "libxdamage",
  "libxcomposite",
  "libxrandr",
  "libxslt",
  "libx11",
  "libxtst",
  "fontconfig",
  "gtk3"
]

[phases.install]
cmds = ["npm install"]

[env]
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
