[build]
builder = "NIXPACKS"
watchPatterns = ["*.js", "*.json", "*.html", "*.cjs"]

[start]
cmd = "node scheduler.cjs"

[phases.setup]
nixPkgs = [
  "nodejs_20",
  "chromium",
  "freetype",
  "harfbuzz",
  "ca-certificates",
  "ttf-font-awesome",
  "glib",
  "nss",
  "alsa-lib",
  "fontconfig",
  "libxcomposite",
  "libxdamage",
  "libxrandr",
  "libxcb",
  "gtk3"
]

[phases.install]
cmds = ["npm install"]
